export type DirectionName = "right" | "left" | "down" | "up" | "down-right" | "down-left" | "up-right" | "up-left";
export type Direction = { name: DirectionName; dr: number; dc: number; label: string };
export type Coordinate = { row: number; col: number };
export type ZoneId = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
export type Tile = Coordinate & { id: string; letter: string; fromRow?: number; injected?: boolean };
export type Board = Array<Array<Tile | null>>;
export type WordOccurrence = { word: string; start: Coordinate; end: Coordinate; direction: Direction; coordinates: Coordinate[]; zone: ZoneId };
export type UsageMap = number[][];
export type ZoneDirectionMap = Record<ZoneId, Partial<Record<DirectionName, number>>>;
export type PreparedMove = {
  key: string;
  boardRevision: number;
  word: string;
  removed: Coordinate[];
  canonicalParent: string;
  incomingByColumn: Record<number, string[]>;
  board: Board;
  available: WordOccurrence[];
  plannedWords: string[];
  rngState: number;
  nextId: number;
  usage: UsageMap;
  zoneUsage: number[];
  zoneActivity: number[];
  recentZones: ZoneId[];
  zoneDirections: ZoneDirectionMap;
  lastOccurrence: WordOccurrence;
  depthTwoValid: boolean;
};
export type GameRuntime = {
  levelId: string;
  board: Board;
  boardRevision: number;
  targets: string[];
  found: string[];
  plannedWords: string[];
  rngState: number;
  nextId: number;
  lastShuffle: boolean;
  reshuffleCount: number;
  recoveryLocked: boolean;
  usage: UsageMap;
  zoneUsage: number[];
  zoneActivity: number[];
  recentZones: ZoneId[];
  zoneDirections: ZoneDirectionMap;
  lastOccurrence: WordOccurrence | null;
  preparedMoves: Record<string, PreparedMove>;
  hintsRemaining: number;
  branchReplans: number;
};
